// Autogenerated from Pigeon (v3.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name
// @dart = 2.12
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/foundation.dart' show WriteBuffer, ReadBuffer;
import 'package:flutter/services.dart';

class HoverRequest {
  HoverRequest({
    this.actionId,
    this.extraData,
  });

  String? actionId;
  Map<String?, String?>? extraData;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['actionId'] = actionId;
    pigeonMap['extraData'] = extraData;
    return pigeonMap;
  }

  static HoverRequest decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return HoverRequest(
      actionId: pigeonMap['actionId'] as String?,
      extraData: (pigeonMap['extraData'] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

class HoverResponse {
  HoverResponse({
    this.responseCode,
    this.errorMessage,
    this.messages,
  });

  int? responseCode;
  String? errorMessage;
  List<String?>? messages;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['responseCode'] = responseCode;
    pigeonMap['errorMessage'] = errorMessage;
    pigeonMap['messages'] = messages;
    return pigeonMap;
  }

  static HoverResponse decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return HoverResponse(
      responseCode: pigeonMap['responseCode'] as int?,
      errorMessage: pigeonMap['errorMessage'] as String?,
      messages: (pigeonMap['messages'] as List<Object?>?)?.cast<String?>(),
    );
  }
}

class _HoverApiCodec extends StandardMessageCodec {
  const _HoverApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is HoverRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is HoverResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return HoverRequest.decode(readValue(buffer)!);
      
      case 129:       
        return HoverResponse.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class HoverApi {
  /// Constructor for [HoverApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HoverApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;

  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _HoverApiCodec();

  Future<HoverResponse> initiateRequest(HoverRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.HoverApi.initiateRequest', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_request]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else if (replyMap['result'] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyMap['result'] as HoverResponse?)!;
    }
  }
}
